/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get accounts
         * @description Get all accounts
         */
        get: operations["getAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account
         * @description Get one account
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Delete account
         * @description Delete one account
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /**
         * Update account
         * @description Update one account
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{id}/establishments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account establishments
         * @description Get account establishments
         */
        get: operations["getAccountEstablishments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account followers
         * @description Get account followers
         */
        get: operations["getAccountFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account followings
         * @description Get account followings
         */
        get: operations["getAccountFollowings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow account
         * @description Follow account
         */
        post: operations["followAccount"];
        /**
         * Unfollow account
         * @description Unfollow account
         */
        delete: operations["unfollowAccount"];
        options?: never;
        head?: never;
        /**
         * Update follow
         * @description Update follow relationship
         */
        patch: operations["updateFollow"];
        trace?: never;
    };
    "/follow-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get follow requests
         * @description Get all follow requests
         */
        get: operations["getFollowRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follow-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get follow request
         * @description Get one follow request
         */
        get: operations["getFollowRequest"];
        put?: never;
        post?: never;
        /**
         * Delete follow request
         * @description Delete one follow request
         */
        delete: operations["deleteFollowRequest"];
        options?: never;
        head?: never;
        /**
         * Update follow request
         * @description Update one follow request
         */
        patch: operations["updateFollowRequest"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get notifications
         * @description Get all notifications
         */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update notification
         * @description Update one notification
         */
        patch: operations["updateNotification"];
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activities
         * @description Get all activities
         */
        get: operations["getActivities"];
        put?: never;
        /**
         * Create activity
         * @description Create activity
         */
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity
         * @description Get one activity
         */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        /**
         * Delete activity
         * @description Delete one activity
         */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        /**
         * Update activity
         * @description Update one activity
         */
        patch: operations["updateActivity"];
        trace?: never;
    };
    "/activity/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity participants
         * @description Get all activity participants
         */
        get: operations["getActivityParticipants"];
        put?: never;
        /**
         * Join activity
         * @description Join activity
         */
        post: operations["joinActivity"];
        /**
         * Leave activity
         * @description Leave activity
         */
        delete: operations["leaveActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity categories
         * @description Get all activity categories
         */
        get: operations["getActivityCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establishments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get establishments
         * @description Get all establishments
         */
        get: operations["getEstablishments"];
        put?: never;
        /**
         * Create establishment
         * @description Create establishment
         */
        post: operations["createEstablishment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establishments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get establishment
         * @description Get one establishment
         */
        get: operations["getEstablishment"];
        put?: never;
        post?: never;
        /**
         * Delete establishment
         * @description Delete one establishment
         */
        delete: operations["deleteEstablishment"];
        options?: never;
        head?: never;
        /**
         * Update establishment
         * @description Update one establishment
         */
        patch: operations["updateEstablishment"];
        trace?: never;
    };
    "/establishments/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get establishment requests
         * @description Get all establishment requests
         */
        get: operations["getEstablishmentRequests"];
        put?: never;
        /**
         * Create establishment request
         * @description Create establishment request
         */
        post: operations["createEstablishmentRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establishments/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete establishment request
         * @description Delete one establishment request
         */
        delete: operations["deleteEstablishmentRequest"];
        options?: never;
        head?: never;
        /**
         * Update establishment request
         * @description Update one establishment request
         */
        patch: operations["updateEstablishmentRequest"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountDTO: components["schemas"]["AccountPersonalDTO"] | components["schemas"]["AccountEnterpriseDTO"];
        AccountPersonalDTO: {
            /**
             * @default other
             * @enum {string}
             */
            gender: "male" | "female" | "other";
            /** Format: date */
            birthdate?: string;
            /**
             * @default personal
             * @enum {string}
             */
            type: "personal";
        } & (components["schemas"]["AccountBase"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "AccountPersonalDTO";
        });
        AccountEnterpriseDTO: {
            /** @default false */
            isVerified: boolean;
            /**
             * @default enterprise
             * @enum {string}
             */
            type: "enterprise";
        } & (components["schemas"]["AccountBase"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "AccountEnterpriseDTO";
        });
        AccountBase: {
            /** Format: uuid */
            id?: string;
            name: string;
            username: string;
            email: string;
            biography?: string;
            avatar?: string;
            website?: string;
            /** @default false */
            isPrivate: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        FollowDTO: {
            /** Format: uuid */
            id: string;
            follower: components["schemas"]["AccountPersonalDTO"];
            following: components["schemas"]["AccountDTO"];
            /** @default true */
            isMuted: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        FollowRequestDTO: {
            /** Format: uuid */
            id: string;
            requestFrom: components["schemas"]["AccountPersonalDTO"];
            requestTo: components["schemas"]["AccountDTO"];
            /**
             * @default pending
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        NotificationDTO: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "follow" | "followRequest" | "establishmentRequest" | "entry" | "activity" | "system";
            content: string;
            /** @default false */
            isRead: boolean;
            owner: components["schemas"]["AccountDTO"];
            relatedAccount?: components["schemas"]["AccountDTO"];
            relatedActivity?: components["schemas"]["ActivityDTO"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AddressDTO: {
            country: string;
            postalCode: string;
            city: string;
            street: string;
            number: string;
            block?: string;
            floor?: string;
            stair?: string;
            door?: string;
            coordinates: {
                /** Format: double */
                latitude?: number;
                /** Format: double */
                longitude?: number;
            };
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ActivityDTO: components["schemas"]["ActivityOnsiteDTO"] | components["schemas"]["ActivityOnlineDTO"];
        ActivityOnsiteDTO: {
            location: components["schemas"]["EstablishmentDTO"] | components["schemas"]["AddressDTO"];
            /** @enum {string} */
            type: "onsite";
        } & (components["schemas"]["ActivityBase"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ActivityOnsiteDTO";
        });
        ActivityOnlineDTO: {
            location: {
                url: string;
            };
            /** @enum {string} */
            type: "online";
        } & (components["schemas"]["ActivityBase"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ActivityOnlineDTO";
        });
        ActivityBase: {
            /** Format: uuid */
            id?: string;
            owner: components["schemas"]["AccountDTO"];
            category: components["schemas"]["ActivityCategoryDTO"];
            title: string;
            description: string;
            images?: string[];
            time: {
                /** Format: date-time */
                start?: string;
                /** Format: date-time */
                end?: string;
            };
            price?: {
                /**
                 * Format: double
                 * @default 0
                 */
                min: number;
                /**
                 * Format: double
                 * @default 0
                 */
                max: number;
                currency?: string;
            };
            participants?: {
                /** Format: int32 */
                min?: number;
                /** Format: int32 */
                max?: number;
            };
            /** @enum {string} */
            language: "en" | "es";
            website?: string;
            /** @default true */
            isDraft: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ActivityCategoryDTO: {
            /** Format: uuid */
            id: string;
            parent?: components["schemas"]["ActivityCategoryDTO"];
            name: string;
            i18nKey: string;
            icon: string;
            color?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ActivityParticipantDTO: {
            /** Format: uuid */
            id: string;
            activity: components["schemas"]["ActivityDTO"];
            account: components["schemas"]["AccountPersonalDTO"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EstablishmentDTO: {
            /** Format: uuid */
            id?: string;
            owner: components["schemas"]["AccountEnterpriseDTO"];
            address: components["schemas"]["AddressDTO"];
            name: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EstablishmentRequestDTO: {
            /** Format: uuid */
            id?: string;
            requestFromAccount: components["schemas"]["AccountEnterpriseDTO"];
            requestForActivity: components["schemas"]["ActivityOnsiteDTO"];
            requestToEstablishment: components["schemas"]["EstablishmentDTO"];
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Bad Request */
                    message?: string;
                    /** @example BAD_REQUEST */
                    code?: string;
                    /**
                     * Format: int32
                     * @example 400
                     */
                    status?: number;
                };
            };
        };
        /** @description Unauthorized */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Unauthorized */
                    message?: string;
                    /** @example UNAUTHORIZED */
                    code?: string;
                    /**
                     * Format: int32
                     * @example 401
                     */
                    status?: number;
                };
            };
        };
        /** @description Forbidden */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Forbidden */
                    message?: string;
                    /** @example FORBIDDEN */
                    code?: string;
                    /**
                     * Format: int32
                     * @example 403
                     */
                    status?: number;
                };
            };
        };
        /** @description Not Found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Not Found */
                    message?: string;
                    /** @example NOT_FOUND */
                    code?: string;
                    /**
                     * Format: int32
                     * @example 404
                     */
                    status?: number;
                };
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Internal Server Error */
                    message?: string;
                    /** @example INTERNAL_SERVER_ERROR */
                    code?: string;
                    /**
                     * Format: int32
                     * @example 500
                     */
                    status?: number;
                };
            };
        };
    };
    parameters: {
        /** @description Account ID */
        accountIdParam: string;
        /** @description Account type */
        accountTypeParam: "personal" | "enterprise";
        /** @description Account name */
        accountNameParam: string;
        /** @description Account username */
        accountUsernameParam: string;
        /** @description Follow request ID */
        followRequestIdParam: string;
        /** @description Notification ID */
        notificationIdParam: string;
        /** @description Establishment ID */
        establishmentIdParam: string;
        /** @description Establishment name */
        establishmentNameParam: string;
        /** @description Establishment address */
        establishmentAddressParam: string;
        /** @description Establishment request ID */
        establishmentRequestIdParam: string;
        /** @description Activity ID */
        activityIdParam: string;
        /** @description Activity title */
        activityTitleParam: string;
        /** @description Activity description */
        activityDescriptionParam: string;
        /** @description Activity category ID */
        activityCategoryIdParam: string;
        /** @description Activity min price */
        activityMinPriceParam: number;
        /** @description Activity max price */
        activityMaxPriceParam: number;
        /** @description Activity language */
        activityLanguageParam: string;
        /** @description Activity type */
        activityTypeParam: "onsite" | "online";
        /** @description Activity time start */
        activityTimeStartParam: string;
        /** @description Activity time end */
        activityTimeEndParam: string;
        /** @description Activity min participants */
        activityMinParcipantsParam: number;
        /** @description Activity max participants */
        activityMaxParcipantsParam: number;
        /** @description Activity min entries */
        activityMinEntriesParam: number;
        /** @description Activity max entries */
        activityMaxEntriesParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAccounts: {
        parameters: {
            query?: {
                /** @description Account type */
                type?: components["parameters"]["accountTypeParam"];
                /** @description Account name */
                name?: components["parameters"]["accountNameParam"];
                /** @description Account username */
                username?: components["parameters"]["accountUsernameParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDTO"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAccountEstablishments: {
        parameters: {
            query?: {
                /** @description Establishment name */
                name?: components["parameters"]["establishmentNameParam"];
                /** @description Establishment address */
                address?: components["parameters"]["establishmentAddressParam"];
            };
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAccountFollowers: {
        parameters: {
            query?: {
                /** @description Account name */
                name?: components["parameters"]["accountNameParam"];
                /** @description Account username */
                username?: components["parameters"]["accountUsernameParam"];
            };
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountPersonalDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAccountFollowings: {
        parameters: {
            query?: {
                /** @description Account name */
                name?: components["parameters"]["accountNameParam"];
                /** @description Account username */
                username?: components["parameters"]["accountUsernameParam"];
            };
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    followAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    unfollowAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["accountIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getFollowRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowRequestDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getFollowRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow request ID */
                id: components["parameters"]["followRequestIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowRequestDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteFollowRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow request ID */
                id: components["parameters"]["followRequestIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateFollowRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow request ID */
                id: components["parameters"]["followRequestIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowRequestDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification ID */
                id: components["parameters"]["notificationIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getActivities: {
        parameters: {
            query?: {
                /** @description Activity type */
                type?: components["parameters"]["activityTypeParam"];
                /** @description Activity title */
                title?: components["parameters"]["activityTitleParam"];
                /** @description Activity description */
                description?: components["parameters"]["activityDescriptionParam"];
                /** @description Activity category ID */
                categoryId?: components["parameters"]["activityCategoryIdParam"];
                /** @description Activity min price */
                minPrice?: components["parameters"]["activityMinPriceParam"];
                /** @description Activity max price */
                maxPrice?: components["parameters"]["activityMaxPriceParam"];
                /** @description Activity time start */
                timeStart?: components["parameters"]["activityTimeStartParam"];
                /** @description Activity time end */
                timeEnd?: components["parameters"]["activityTimeEndParam"];
                /** @description Activity min participants */
                minParticipants?: components["parameters"]["activityMinParcipantsParam"];
                /** @description Activity max participants */
                maxParticipants?: components["parameters"]["activityMaxParcipantsParam"];
                /** @description Activity min entries */
                minEntries?: components["parameters"]["activityMinEntriesParam"];
                /** @description Activity max entries */
                maxEntries?: components["parameters"]["activityMaxEntriesParam"];
                /** @description Activity language */
                language?: components["parameters"]["activityLanguageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getActivityParticipants: {
        parameters: {
            query?: {
                /** @description Account name */
                name?: components["parameters"]["accountNameParam"];
                /** @description Account username */
                username?: components["parameters"]["accountUsernameParam"];
            };
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityParticipantDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    joinActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityParticipantDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    leaveActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: components["parameters"]["activityIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getActivityCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityCategoryDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEstablishments: {
        parameters: {
            query?: {
                /** @description Establishment name */
                name?: components["parameters"]["establishmentNameParam"];
                /** @description Establishment address */
                address?: components["parameters"]["establishmentAddressParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createEstablishment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishmentDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEstablishment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Establishment ID */
                id: components["parameters"]["establishmentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentDTO"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteEstablishment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Establishment ID */
                id: components["parameters"]["establishmentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateEstablishment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Establishment ID */
                id: components["parameters"]["establishmentIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishmentDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEstablishmentRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentRequestDTO"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createEstablishmentRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishmentRequestDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentRequestDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteEstablishmentRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Establishment request ID */
                id: components["parameters"]["establishmentRequestIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateEstablishmentRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Establishment request ID */
                id: components["parameters"]["establishmentRequestIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishmentRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishmentRequestDTO"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
